# Generated by Django 5.0.4 on 2024-04-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('lecture_teacher', models.CharField(blank=True, max_length=255)),
                ('practical_teacher', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='course',
            field=models.CharField(default='Unknown', max_length=300),
        ),
    ]
