# Generated by Django 5.0.4 on 2024-04-05 16:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_course_notes_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
